### ISSUE TITLE
Consider using application defaults rather than altering the binary

### ISSUE THREAD

**Issue by natbro** [Trsvsr/MetalHUDEnabler#1]
Cool tool, thanks for helping folks enable the HUD!
Since you initially wrote this we released a tech-talk that describes some more ways to enable the HUD: https://developer.apple.com/videos/play/tech-talks/110339.
The current method of patching the binary nukes the code-signing and causes some trouble with updates and prevents some apps from running - you may find that you're able to use the application's bundle-id found in its Info.plist file to set user defaults to enable the HUD for specific applications rather than touching the application bundle at all.
You can catch me at natbro@apple.com if you have any questions or hit any bumps - keep having fun!

**Comment by Trsvsr** [comment]
Hey Nat, thanks so much for sending a link to the tech-talk! This is definitely something I can look into.

**Comment by Trsvsr** [comment]
I've pushed a new release that utilizes user defaults, thanks again for the heads up! Closing this issue.

**Comment by natbro** [comment]
nice, thanks @Trsvsr !
