### ISSUE TITLE
no joy

### ISSUE THREAD

**Issue by nivepl** [Trsvsr/MetalHUDEnabler#2]
What am I doing wrong?
![ds](https://github.com/Trsvsr/MetalHUDEnabler/assets/7541409/b12d0432-bd1f-45a5-ae12-2fab7362880e)

**Comment by Trsvsr** [comment]
The instructions are included in each release.

**If the executable does not run on the first attempt:**

1. Execute `chmod 0755 ./MetalHUDEnabler` in a terminal
2. Right click on MetalHUDEnabler wherever you saved it in Finder and click "Open"
3. Try executing it again in a terminal afterwards

**Comment by nivepl** [comment]
No effect
![dsds](https://github.com/Trsvsr/MetalHUDEnabler/assets/7541409/c99d2722-bf6d-4fa9-99d6-5b2a9af52d49)

**Comment by Tc20025** [comment]
Hi...
        Im user of MetalHUDEnabler on Mac and I appreciate your hard work..... well I'm here to ask that could it work on iOS device to if we extract the app on Mac and edit plist and restore back on iOS device and since its permanent it will stay there forever so could you please tell me sir how to do that
