### ISSUE TITLE
MetalHUD for iOS

### ISSUE THREAD

**Issue by Tc20025** [Trsvsr/MetalHUDEnabler#3]
Hi...
Im user of MetalHUDEnabler on Mac and I appreciate your hard work..... well I'm here to ask that could it work on iOS device to if we extract the app on Mac and edit plist and restore back on iOS device and since its permanent it will stay there forever so could you please tell me sir how to do that

**Comment by Trsvsr** [comment]
I think you can use the Developer settings on an iOS device to enable the Metal HUD. Other than that, I remember back in the day you could modify user preferences through restoring modified iOS device backups, but I am not sure if that would actually even work for what MetalHUDEnabler does. I'll leave that as an exercise for anyone curious enough to try.
