### ISSUE TITLE
Metal Performance HUD custom information?

### ISSUE THREAD

**Issue by s7v3n7** [Trsvsr/MetalHUDEnabler#4]
Hi, Thanks for sharing this. Just wondering if you know of any workaround to remove the additional information shown after FPS and the GPU memory footprint? It's taking up so much space on the screen and blocking some important information. Would be ideal to just keep the FPS up to the GPU memory footprint.

<img width="243" alt="Screenshot 2023-12-22 at 12 54 57 am" src="https://github.com/Trsvsr/MetalHUDEnabler/assets/143871914/4aa5ed77-5929-41e1-956c-ef414c1e9e54">

**Comment by Trsvsr** [comment]
Sorry for the late response. That information only appears when running a game using D3DMetal, and as far as I'm aware there is no way to hide it other than disabling the HUD altogether.
