### ISSUE TITLE
Cant Globally Disable

### ISSUE THREAD

**Issue by ItsYeBoi20** [Trsvsr/MetalHUDEnabler#5]
I cant disable MetalHUDEnabler gloabally for every application. Geforce NOW for example has the HUD on by default, which cant even be turned off. Trying to manually disable the .app leads to:
> Domain (com.nvidia.gfnpc.mall) not found.
> Defaults have not been changed.

A option to disable/enable the ENTIRE program would be great, as I have to uninstall now, because I cant get the HUD removed for Geforce NOW..

**Comment by Trsvsr** [comment]
If you're getting a "Domain not found" error, then somehow the user preferences file for GeForce NOW (Located at `~/Library/Preferences/com.nvidia.gfnpc.mall.plist`) was deleted. I've tested this on GeForce NOW and it works as expected.
